-- Known boss names across Classic (vanilla) and TBC dungeons/raids, used by
-- MacroSwap's "Boss" / "Trash" target modes. Lowercase keys.
-- This is plain data - if a name's wrong or missing, just edit this file.

MacroSwap_Bosses = {
    -- Hellfire Ramparts
    ["watchkeeper gargolmar"] = true,
    ["omor the unscarred"] = true,
    ["vazruden"] = true,
    ["nazan"] = true,
    -- The Blood Furnace
    ["the maker"] = true,
    ["broggok"] = true,
    ["keli'dan the breaker"] = true,
    -- Shattered Halls
    ["grand warlock nethekurse"] = true,
    ["blood guard porung"] = true,
    ["warbringer o'mrogg"] = true,
    ["warchief kargath bladefist"] = true,
    -- The Slave Pens
    ["mennu the betrayer"] = true,
    ["rokmar the crackler"] = true,
    ["quagmirran"] = true,
    -- The Underbog
    ["hungarfen"] = true,
    ["ghaz'an"] = true,
    ["swamplord musel'ek"] = true,
    ["the black stalker"] = true,
    -- The Steamvault
    ["hydromancer thespia"] = true,
    ["mekgineer steamrigger"] = true,
    ["warlord kalithresh"] = true,
    -- Mana-Tombs
    ["pandemonius"] = true,
    ["tavarok"] = true,
    ["nexus-prince shaffar"] = true,
    -- Auchenai Crypts
    ["shirrak the dead watcher"] = true,
    ["exarch maladaar"] = true,
    -- Sethekk Halls
    ["darkweaver syth"] = true,
    ["talon king ikiss"] = true,
    ["anzu"] = true,
    -- Shadow Labyrinth
    ["ambassador hellmaw"] = true,
    ["blackheart the inciter"] = true,
    ["grandmaster vorpil"] = true,
    ["murmur"] = true,
    -- Old Hillsbrad Foothills
    ["lieutenant drake"] = true,
    ["captain skarloc"] = true,
    ["epoch hunter"] = true,
    -- The Black Morass
    ["chrono lord deja"] = true,
    ["temporus"] = true,
    ["aeonus"] = true,
    -- The Mechanar
    ["mechano-lord capacitus"] = true,
    ["nethermancer sepethrea"] = true,
    ["pathaleon the calculator"] = true,
    -- The Botanica
    ["commander sarannis"] = true,
    ["high botanist freywinn"] = true,
    ["thorngrin the tender"] = true,
    ["laj"] = true,
    -- The Arcatraz
    ["zereketh the unbound"] = true,
    ["dalliah the doomsayer"] = true,
    ["wrath-scryer soccothrates"] = true,
    ["harbinger skyriss"] = true,
    -- Magisters' Terrace
    ["selin fireheart"] = true,
    ["vexallus"] = true,
    ["priestess delrissa"] = true,
    ["kael'thas sunstrider"] = true, -- also Tempest Keep raid version below (same name)

    -- Karazhan
    ["attumen the huntsman"] = true,
    ["midnight"] = true,
    ["moroes"] = true,
    ["maiden of virtue"] = true,
    ["the big bad wolf"] = true,
    ["the curator"] = true,
    ["terestian illhoof"] = true,
    ["netherspite"] = true,
    ["prince malchezaar"] = true,
    ["nightbane"] = true,

    -- Gruul's Lair
    ["high king maulgar"] = true,
    ["gruul the dragonkiller"] = true,

    -- Magtheridon's Lair
    ["magtheridon"] = true,

    -- Serpentshrine Cavern
    ["hydross the unstable"] = true,
    ["the lurker below"] = true,
    ["leotheras the blind"] = true,
    ["fathom-lord karathress"] = true,
    ["morogrim tidewalker"] = true,
    ["lady vashj"] = true,

    -- Tempest Keep (raid)
    ["al'ar"] = true,
    ["void reaver"] = true,
    ["high astromancer solarian"] = true,

    -- Mount Hyjal
    ["rage winterchill"] = true,
    ["anetheron"] = true,
    ["kaz'rogal"] = true,
    ["azgalor"] = true,
    ["archimonde"] = true,

    -- Black Temple
    ["high warlord naj'entus"] = true,
    ["supremus"] = true,
    ["shade of akama"] = true,
    ["teron gorefiend"] = true,
    ["gurtogg bloodboil"] = true,
    ["reliquary of souls"] = true,
    ["mother shahraz"] = true,
    ["the illidari council"] = true,
    ["illidan stormrage"] = true,

    -- Zul'Aman
    ["nalorakk"] = true,
    ["akil'zon"] = true,
    ["jan'alai"] = true,
    ["halazzi"] = true,
    ["hex lord malacrass"] = true,
    ["zul'jin"] = true,

    -- Sunwell Plateau
    ["kalecgos"] = true,
    ["brutallus"] = true,
    ["felmyst"] = true,
    ["lady sacrolash"] = true,
    ["grand warlock alythess"] = true,
    ["m'uru"] = true,
    ["entropius"] = true,
    ["kil'jaeden"] = true,

    -- Notable TBC world bosses
    ["doomwalker"] = true,
    ["doom lord kazzak"] = true,

    -- ===================== Classic (vanilla) content =====================

    -- Ragefire Chasm
    ["oggleflint"] = true,
    ["taragaman the hungerer"] = true,
    ["jergosh the invoker"] = true,
    ["bazzalan"] = true,
    -- The Deadmines
    ["rhahk'zor"] = true,
    ["sneed"] = true,
    ["gilnid"] = true,
    ["mr. smite"] = true,
    ["captain greenskin"] = true,
    ["edwin vancleef"] = true,
    -- Wailing Caverns
    ["lady anacondra"] = true,
    ["lord cobrahn"] = true,
    ["lord pythas"] = true,
    ["lord serpentis"] = true,
    ["skum"] = true,
    ["verdan the everliving"] = true,
    ["mutanus the devourer"] = true,
    -- Shadowfang Keep
    ["rethilgore"] = true,
    ["razorclaw the butcher"] = true,
    ["baron silverlaine"] = true,
    ["commander springvale"] = true,
    ["odo the blindwatcher"] = true,
    ["fenrus the devourer"] = true,
    ["archmage arugal"] = true,
    -- Blackfathom Deeps
    ["ghamoo-ra"] = true,
    ["lady sarevess"] = true,
    ["gelihast"] = true,
    ["lorgus jett"] = true,
    ["baron aquanis"] = true,
    ["old serra'kis"] = true,
    ["aku'mai"] = true,
    -- The Stockade
    ["kam deepfury"] = true,
    ["targorr the dread"] = true,
    ["bazil thredd"] = true,
    ["hamhock"] = true,
    ["dextren ward"] = true,
    -- Gnomeregan
    ["grubbis"] = true,
    ["viscous fallout"] = true,
    ["electrocutioner 6000"] = true,
    ["crowd pummeler 9-60"] = true,
    ["mekgineer thermaplugg"] = true,
    -- Razorfen Kraul
    ["overlord ramtusk"] = true,
    ["death speaker jargba"] = true,
    ["roogug"] = true,
    ["aggem thorncurse"] = true,
    ["blind hunter"] = true,
    ["charlga razorflank"] = true,
    -- Scarlet Monastery
    ["interrogator vishas"] = true,
    ["bloodmage thalnos"] = true,
    ["houndmaster loksey"] = true,
    ["arcanist doan"] = true,
    ["herod"] = true,
    ["high inquisitor fairbanks"] = true,
    ["scarlet commander mograine"] = true,
    ["high inquisitor whitemane"] = true,
    -- Razorfen Downs
    ["tuten'kash"] = true,
    ["mordresh fire eye"] = true,
    ["amnennar the coldbringer"] = true,
    ["ragglesnout"] = true,
    ["glutton"] = true,
    -- Uldaman
    ["revelosh"] = true,
    ["ironaya"] = true,
    ["obsidian sentinel"] = true,
    ["ancient stone keeper"] = true,
    ["galgann firehammer"] = true,
    ["archaedas"] = true,
    -- Zul'Farrak
    ["antu'sul"] = true,
    ["theka the martyr"] = true,
    ["witch doctor zum'rah"] = true,
    ["nekrum gutchewer"] = true,
    ["shadowpriest sezz'ziz"] = true,
    ["sandfury executioner"] = true,
    ["chief ukorz sandscalp"] = true,
    ["gahz'rilla"] = true,
    -- Maraudon
    ["noxxion"] = true,
    ["razorlash"] = true,
    ["lord vyletongue"] = true,
    ["landslide"] = true,
    ["tinkerer gizlock"] = true,
    ["rotgrip"] = true,
    ["celebras the cursed"] = true,
    ["princess theradras"] = true,
    -- Temple of Atal'Hakkar (Sunken Temple)
    ["jammal'an the prophet"] = true,
    ["ogom the wretched"] = true,
    ["hazza'rah"] = true,
    ["shade of eranikus"] = true,
    ["atal'alarion"] = true,
    -- Blackrock Depths
    ["lord roccor"] = true,
    ["bael'gar"] = true,
    ["high interrogator gerstahn"] = true,
    ["houndmaster grebmar"] = true,
    ["grizzle"] = true,
    ["pyromancer loregrain"] = true,
    ["fineous darkvire"] = true,
    ["ambassador flamelash"] = true,
    ["general angerforge"] = true,
    ["golem lord argelmach"] = true,
    ["emperor dagran thaurissan"] = true,
    ["princess moira thaurissan"] = true,
    -- Blackrock Spire (Upper and Lower)
    ["highlord omokk"] = true,
    ["shadow hunter vosh'gajin"] = true,
    ["war master voone"] = true,
    ["mother smolderweb"] = true,
    ["overlord wyrmthalak"] = true,
    ["halycon"] = true,
    ["quartermaster zigris"] = true,
    ["pyroguard emberseer"] = true,
    ["solakar flamewreath"] = true,
    ["warchief rend blackhand"] = true,
    ["gyth"] = true,
    ["the beast"] = true,
    ["general drakkisath"] = true,
    -- Scholomance
    ["kirtonos the herald"] = true,
    ["jandice barov"] = true,
    ["rattlegore"] = true,
    ["marduk blackpool"] = true,
    ["vectus"] = true,
    ["ras frostwhisper"] = true,
    ["lorekeeper polkelt"] = true,
    ["instructor malicia"] = true,
    ["doctor theolen krastinov"] = true,
    ["lord alexei barov"] = true,
    ["the ravenian"] = true,
    ["darkmaster gandling"] = true,
    -- Stratholme
    ["skul"] = true,
    ["hearthsinger forresten"] = true,
    ["postmaster malown"] = true,
    ["timmy the cruel"] = true,
    ["malor the zealous"] = true,
    ["cannon master willey"] = true,
    ["baroness anastari"] = true,
    ["nerub'enkan"] = true,
    ["maleki the pallid"] = true,
    ["ramstein the gorger"] = true,
    ["baron rivendare"] = true,
    ["archivist galford"] = true,
    ["grand crusader dathrohan"] = true,
    ["balnazzar"] = true,
    -- Dire Maul
    ["tendris warpwood"] = true,
    ["magister kalendris"] = true,
    ["lethtendris"] = true,
    ["zevrim thornhoof"] = true,
    ["hydrospawn"] = true,
    ["guard mol'dar"] = true,
    ["stomper kreeg"] = true,
    ["captain kromcrush"] = true,
    ["prince tortheldrin"] = true,
    ["guard fengus"] = true,
    ["guard slip'kik"] = true,
    ["tsu'zee"] = true,
    ["knot thimblejack"] = true,
    ["king gordok"] = true,
    ["cho'rush the observer"] = true,
    ["pusillin"] = true,

    -- Molten Core
    ["lucifron"] = true,
    ["magmadar"] = true,
    ["gehennas"] = true,
    ["garr"] = true,
    ["baron geddon"] = true,
    ["shazzrah"] = true,
    ["sulfuron harbinger"] = true,
    ["golemagg the incinerator"] = true,
    ["majordomo executus"] = true,
    ["ragnaros"] = true,

    -- Onyxia's Lair
    ["onyxia"] = true,

    -- Blackwing Lair
    ["razorgore the untamed"] = true,
    ["vaelastrasz the corrupt"] = true,
    ["broodlord lashlayer"] = true,
    ["firemaw"] = true,
    ["ebonroc"] = true,
    ["flamegor"] = true,
    ["chromaggus"] = true,
    ["nefarian"] = true,

    -- Zul'Gurub
    ["high priest venoxis"] = true,
    ["high priestess jeklik"] = true,
    ["high priest thekal"] = true,
    ["high priestess mar'li"] = true,
    ["bloodlord mandokir"] = true,
    ["gahz'ranka"] = true,
    ["hakkar"] = true,
    ["jin'do the hexxer"] = true,
    ["arlokk"] = true,
    ["renataki"] = true,
    ["wushoolay"] = true,
    ["gri'lek"] = true,

    -- Ruins of Ahn'Qiraj (AQ20)
    ["kurinnaxx"] = true,
    ["general rajaxx"] = true,
    ["moam"] = true,
    ["buru the gorger"] = true,
    ["ayamiss the hunter"] = true,
    ["ossirian the unscarred"] = true,

    -- Temple of Ahn'Qiraj (AQ40)
    ["the prophet skeram"] = true,
    ["lord kri"] = true,
    ["vem"] = true,
    ["princess yauj"] = true,
    ["battleguard sartura"] = true,
    ["fankriss the unyielding"] = true,
    ["viscidus"] = true,
    ["princess huhuran"] = true,
    ["the twin emperors"] = true,
    ["vek'lor"] = true,
    ["vek'nilash"] = true,
    ["ouro"] = true,
    ["c'thun"] = true,

    -- Naxxramas (original)
    ["anub'rekhan"] = true,
    ["grand widow faerlina"] = true,
    ["maexxna"] = true,
    ["noth the plaguebringer"] = true,
    ["heigan the unclean"] = true,
    ["loatheb"] = true,
    ["instructor razuvious"] = true,
    ["gothik the harvester"] = true,
    ["highlord mograine"] = true,
    ["lady blaumeux"] = true,
    ["sir zeliek"] = true,
    ["thane korth'azz"] = true,
    ["patchwerk"] = true,
    ["grobbulus"] = true,
    ["gluth"] = true,
    ["thaddius"] = true,
    ["sapphiron"] = true,
    ["kel'thuzad"] = true,
}
